"""campos de verificacion

Revision ID: 75c360b8d526
Revises: feb38123d929
Create Date: 2026-02-05 20:22:30.563645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c360b8d526'
down_revision = 'feb38123d929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('codigo_verificacion', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('codigo_expiracion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('codigo_expiracion')
        batch_op.drop_column('codigo_verificacion')
        batch_op.drop_column('verificado')

    # ### end Alembic commands ###
