"""recuperar contraseñas

Revision ID: 816dbfcba2d9
Revises: 75c360b8d526
Create Date: 2026-02-12 22:22:25.886752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816dbfcba2d9'
down_revision = '75c360b8d526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_recuperacion', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('codigo_recuperacion_expiracion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('codigo_recuperacion_expiracion')
        batch_op.drop_column('codigo_recuperacion')

    # ### end Alembic commands ###
