"""columna categoria

Revision ID: 82247e2526ef
Revises: 70ca9ea42f7f
Create Date: 2026-01-22 19:42:42.185275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82247e2526ef'
down_revision = '70ca9ea42f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
